### ISSUE TITLE
aws-eks-nodeagent crashing 

### ISSUE THREAD

**Issue by Paso** [aws/aws-network-policy-agent#101]
**What happened**:
After upgrading our EKS cluster to 1.28 and aws-vpc-cni to 1.15.0 using helm ( + coredns + kube-proxy + aws ebs cni ) the aws-eks-nodeagent in the vpc-cni is in a CrashLoopBackOff.  

The vpc-cni helm chart uses all default values, including `enableNetworkPolicy=false`.

The aws-node container is running without any problems.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: v1.27.1-eks-2f008fe
Server Version: v1.28.2-eks-f8587cb

- CNI Version
helm.sh/chart=aws-vpc-cni-1.15.1

- OS (e.g: `cat /etc/os-release`):
Amazon Linux 2
(default from helm chart)

- Kernel (e.g. `uname -a`):
5.10.192-183.736.amzn2.x86_64
(default from helm chart)

**Logs**
From: `kubectl -nkube-system logs aws-node-t6mnp aws-eks-nodeagent`:
```
{"level":"info","ts":"2023-10-18T15:58:26.518Z","caller":"runtime/asm_amd64.s:1598","msg":"version","GitVersion":"","GitCommit":"","BuildDate":""}
2023-10-18 15:58:26.531517744 +0000 UTC Logger.check error: failed to get caller
2023-10-18 15:58:26.532104521 +0000 UTC Logger.check error: failed to get caller
2023-10-18 16:00:26.534968177 +0000 UTC Logger.check error: failed to get caller
2023-10-18 16:00:26.535095653 +0000 UTC Logger.check error: failed to get caller
2023-10-18 16:00:26.535256037 +0000 UTC Logger.check error: failed to get caller
2023-10-18 16:00:26.535392471 +0000 UTC Logger.check error: failed to get caller
2023-10-18 16:00:26.535489589 +0000 UTC Logger.check error: failed to get caller
2023-10-18 16:00:26.535513138 +0000 UTC Logger.check error: failed to get caller
```

From `kubectl -nkube-system describe pod aws-node-t6mnp`:
```
  aws-eks-nodeagent:
    Container ID:  containerd://98f348dcbc301b48e062ebbdf75585e160315fd7119f13be94acaf464140e3d2
    Image:         602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-network-policy-agent:v1.0.4
    Image ID:      602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-network-policy-agent@sha256:80657a95ac77443c150763ea5432889944073f0390f9213239d58891b82d0ea2
    Port:          <none>
    Host Port:     <none>
    Args:
      --enable-ipv6=false
      --enable-network-policy=false
      --enable-cloudwatch-logs=false
      --enable-policy-event-logs=false
      --metrics-bind-addr=:8162
      --health-probe-bind-addr=:8163
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 18 Oct 2023 18:12:39 +0200
      Finished:     Wed, 18 Oct 2023 18:14:39 +0200
    Ready:          False
    Restart Count:  17
    Requests:
      cpu:  25m
    Environment:
      MY_NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /host/opt/cni/bin from cni-bin-dir (rw)
      /sys/fs/bpf from bpf-pin-path (rw)
      /var/log/aws-routed-eni from log-dir (rw)
      /var/run/aws-node from run-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4xfhs (ro)
```

**Comment by jayanthvn** [comment]
Can you please share the o/p -

```
kubectl describe configmap amazon-vpc-cni -n kube-system
```

```
kubectl get crd | grep policyendpoints
```

Also please do share the network policy agent logs, you can use the node logs collector script - 

```
sudo bash /opt/cni/bin/aws-cni-support.sh
```

**Comment by Paso** [comment]
`$ kubectl describe configmap amazon-vpc-cni -n kube-system`
```
Name:         amazon-vpc-cni
Namespace:    kube-system
Labels:       app.kubernetes.io/instance=aws-vpc-cni
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=aws-node
              app.kubernetes.io/version=v1.15.1
              helm.sh/chart=aws-vpc-cni-1.15.1
              k8s-app=aws-node
Annotations:  meta.helm.sh/release-name: aws-vpc-cni
              meta.helm.sh/release-namespace: kube-system

Data
====
enable-network-policy-controller:
----
false
enable-windows-ipam:
----
false

BinaryData
====

Events:  <none>
```

`kubectl get crd | grep policyendpoints` returns nothing.

It's difficult to access the logs as the container crashes quite fast, any ideas how I can get them out?

**Comment by achevuru** [comment]
`PolicyEndpoints` is a required resource similar to `EniConfig` and we expect `PolicyEndpoints` resource to be present if you upgraded using latest helm chart.

https://github.com/aws/eks-charts/blob/master/stable/aws-vpc-cni/crds/customresourcedefinition.yaml#L22

**Comment by Paso** [comment]
That is strange. I have checked the helm chart I'm using and it is the correct version with the CRDs, but they are not installed.

I do have these that may be related?

`$ kubectl get crd | grep aws`
```
cninodes.vpcresources.k8s.aws                     2023-08-14T19:24:42Z
securitygrouppolicies.vpcresources.k8s.aws        2021-02-18T12:17:28Z
```

**Comment by Paso** [comment]
I'm a helm beginner but I find it unclear if CRDs are applied when doing a helm upgrade. Is the recommended way of upgrading this chart doing a uninstall+install instead of a upgrade?

**Comment by Paso** [comment]
From this documentation it seems that one needs a pre-upgrade hook to install CRDs on helm upgrade and I can't find one of those in the chart.

https://handbook.giantswarm.io/docs/dev-and-releng/app-developer-processes/handle_crds_with_helm_3/

**Comment by jayanthvn** [comment]
@Paso Can we close this issue now?

**Comment by Paso** [comment]
My suggestion it that you make it clear in the documentation that you may have to uninstall+reinstall or in other way install the CRDs manually on an upgrade.

**Comment by jayanthvn** [comment]
Agreed, we will add it in the documentation.
