### ISSUE TITLE
aws-network-policy-agent image is not published to ECR Public repo

### ISSUE THREAD

**Issue by sbocinec** [aws/aws-network-policy-agent#119]
**What happened**:

`v1.14` [introduced](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.14.0) a new NetworkPolicy agent, but in contrast to the other VPC CNI images (`amazon-k8s-cni` and `amazon-k8s-cni-init`),the `aws-network-policy-agent`  image is not published to the [public ECR registry](https://gallery.ecr.aws/eks?page=1)

We have special use cases where we can't use private ECR repos so it's currently blocking us from deploying the helm chart with NetworkPolicy enabled as we can't override the default `nodeAgent.image` with the ECR public repo in `nodeAgent.image.override`.

**Attach logs**

**What you expected to happen**:

`aws-network-policy-agent` should be published to Public ECR registry together with the other VPC CNI images.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- CNI Version: 1.14+
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

**Comment by jdn5126** [comment]
Thanks for the call out @sbocinec. I will work on getting the network policy agent images published. Should be completed by the end of the day

**Comment by jdn5126** [comment]
@sbocinec all images are published to https://gallery.ecr.aws/eks/aws-network-policy-agent now, including the latest image, `v1.0.5`, which will ship with VPC CNI `v1.15.3`

**Comment by sbocinec** [comment]
Thank you @jdn5126 for such a prompt help & fix :raised_hands: :tada:
