### ISSUE TITLE
Network Policy Blocking Cronjob Pods' Communication After vpc-cni 1.15.3 Upgrade

### ISSUE THREAD

**Issue by atilsensalduz** [aws/aws-network-policy-agent#130]
After upgrading to vpc-cni version 1.15.3, I've encountered a problem where my cronjob pods' communication is unexpectedly blocked, despite having the correct network policies in place. Strangely, this issue did not occur prior to the upgrade. I've also verified the policyendpoints and can confirm that the IP addresses of my cronjob pods are correctly exist in policyendpoints. I'm wondering if this is a known issue with the new version 🤔

**Comment by achevuru** [comment]
@atilsensalduz No, we're not aware of any issue with the 1.15.3. Can you share the network policy agent logs from the node where these cronjob pods are running? You can mail them to `k8s-awscni-triage@amazon.com`. Please also share the describe o/p of corresponding `policyEndpoint` resources as well. Thanks.

**Comment by jayanthvn** [comment]
This is possibly happening because of the issue pointed here #131. We can confirm with the logs you send.

**Comment by jdn5126** [comment]
Closing as fixed
