### ISSUE TITLE
No release v1.0.7 description

### ISSUE THREAD

**Issue by c13** [aws/aws-network-policy-agent#176]
Hello, I see that amazon-vpc-cni-k8s uses aws-network-policy-agent:v1.0.7 starting v1.15.5, but this aws-network-policy-agent version wasn't released in the corresponding GitHub repo for some reason. So, we can't see a list of changes in that release.
https://github.com/aws/amazon-vpc-cni-k8s/releases

**Comment by jayanthvn** [comment]
Thanks for pointing it out. We are cutting the release soon.

**Comment by jaydeokar** [comment]
Created the github release for v1.0.7. Thanks for reporting @c13 
Closing this issue
