### ISSUE TITLE
"Check error: failed to get caller" error after VPC CNI plugin version upgrade (V1.18.0)

### ISSUE THREAD

**Issue by madhavpersistent** [aws/aws-network-policy-agent#247]
Issue Description:
After upgrading the VPC CNI plugin from v1.15.0 to v1.18.0 in our EKS cluster (upgraded from version 1.26 to 1.27), we are encountering an issue with one of the init containers. The container fails with the following error: “check error: failed to get caller”. This issue persists despite claims that it was addressed in a recent GitHub pull request.

Previous Interaction:
This issue is similar to one we experienced previously during an update from CNI version v1.15.0 to v1.16.0 while upgrading the EKS Cluster from version 1.25 to 1.27. The problem was supposedly resolved according to AWS support referencing GitHub pull request #168.

Current Problem
Despite the resolution mentioned in the GitHub pull request, the error is reoccurring in the latest upgrade scenario. 

Steps to Reproduce
1. Upgrade EKS cluster from version 1.27 to 1.28.
2. Upgrade VPC CNI plugin from v1.15.0 to v1.18.0.
3. Observe the initiation of containers.

Expected Behavior:
The init containers should start without any errors post upgrade.

Actual Behavior:
One of the init containers fails to start, logging the following error: “check error: failed to get caller.”

Additional Information
• EKS Cluster Version: 1.28
• VPC CNI Plugin Version: v1.18.0
• Error Logs: 
**"{"level":"info","ts":"2024-04-0914:08:52.66Z","caller":"metrics/metrics.go:23","msg":"Serving metrics on ","port":6160}
2024-04-09 14:08:52.6406 +0000 UTC Logger.check error: failed to get caller"**

Questions
1. Is the VPC CNI plugin version v1.18.0 fully compatible with EKS version 1.28?
2. Was the issue resolved in PR #168 supposed to cover this scenario?
3. What could be the reason for this error recurring?

**Comment by achevuru** [comment]
@madhavpersistent Can you elaborate on ` container fails with the following error: “check error: failed to get caller”.`? What is failing? Is CNI pod not moving to `Running` state? Above log message shouldn't contribute to any functionality issue and more of a false flag that we need to address..

**Comment by achevuru** [comment]
@xamroc You should ideally see these just once during bootup. If you're seeing them frequently, please check if `aws-eks-nodeagent` container is constantly restarting for some reason in your cluster

**Comment by xamroc** [comment]
@achevuru It isn't. The `aws-node` pod is running without restarts. Both containers inside it are running fine as well.
They just constantly log `Logger.check error: failed to get caller`.

I've already worked with AWS Support on this and they can provide those details. They've captured the logs from our nodes as well if that helps.

**Comment by jayanthvn** [comment]
This issue is fixed with this PR - https://github.com/aws/aws-network-policy-agent/pull/254. We are working on the release and should have the released image by this week

**Comment by jayanthvn** [comment]
@connorharkness95  - Are you seeing the error with init container and not aws-eks-nodeagent?

**Comment by jayanthvn** [comment]
Yes the fix is released with latest network policy agent - 1.1.2 - https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.18.2

**Comment by doctornkz-intelas** [comment]
Hello, I double-checked the issue, and it's still here, sorry:
`2025-07-08 18:21:34.133713035 +0000 UTC Logger.check error: failed to get caller`
Versions:
```
aws-network-policy-agent:v1.2.2
amazon-k8s-cni:v1.19.6-eksbuild.1
amazon-k8s-cni-init:v1.19.6-eksbuild.1
```
Arguments:
```
--enable-ipv6=false
--enable-network-policy=false
--enable-cloudwatch-logs=false
--enable-policy-event-logs=false
--log-file=/var/log/aws-routed-eni/network-policy-agent.log
--metrics-bind-addr=:8162
--health-probe-bind-addr=:8163
--conntrack-cache-cleanup-period=300
--log-level=debug
```

**Comment by FlorinAsavoaie** [comment]
Encountering this on eks 1.33 with vpc-cni v1.20.1-eksbuild.1.

**Comment by ZivRechnitser** [comment]
Me too, eks 1.30 with vpc-cni v1.20.1-eksbuild.3

**Comment by cShirley14** [comment]
Still seeing it on eks 1.32 vpc-cni v1.20.1-eksbuild.3
