### ISSUE TITLE
does aws-network-policy-agent work without vmlinux.h?

### ISSUE THREAD

**Issue by developer-guy** [aws/aws-network-policy-agent#249]
Hello folks👋

At the line [#32](https://github.com/aws/aws-network-policy-agent/blob/b3d2257ca51e859f6f559760dc6ddc2772e29499/Dockerfile#L32) in Dockerfile `make vmlinuxh` tries to run [bpftool btf dump file ..](https://github.com/aws/aws-network-policy-agent/blob/b3d2257ca51e859f6f559760dc6ddc2772e29499/Makefile#L128) and it causes the following problem in our GitHub Actions workflow:

```
2024/04/13 20:08:33 INFO /sys/kernel/btf/vmlinux: cannot open `/sys/kernel/btf/vmlinux' (No such file or directory)
2024/04/13 20:08:33 INFO bpftool btf dump file /sys/kernel/btf/vmlinux format c > /home/build/pkg/ebpf/c/vmlinux.h
2024/04/13 20:08:33 WARN Error: failed to load BTF from /sys/kernel/btf/vmlinux: No such file or directory
```

So the questions are:

- Would you mind giving me some ideas to sort out this problem?
- If this is smth that we cannot fix atm is this required for the application to be running?

Thanks!

**Comment by jayanthvn** [comment]
@developer-guy - Do you know the kernel version where the build is happening?

Since looks like `/sys/kernel/btf/vmlinux` is missing.

**Comment by orsenthil** [comment]
We call out the minimal kernel version and requirements in our docs here

>  .Minimum Linux kernel version Your nodes must have Linux kernel version 5.10 or later. You can check your kernel version with uname -r. If you’re using the latest versions of the Amazon EKS optimized Amazon Linux, Amazon EKS optimized accelerated Amazon Linux AMIs, and Bottlerocket AMIs, they already have the required kernel version.

> + The Amazon EKS optimized accelerated Amazon Linux AMI version v20231116 or later have kernel version 5.10.

https://docs.aws.amazon.com/eks/latest/userguide/cni-network-policy-configure.html

If your kernel is older and doesn't have vmlinux, then NP agent may not work for you.

**Comment by orsenthil** [comment]
@developer-guy if you are using a different OS. can you verify if this patch https://github.com/aws/aws-network-policy-agent/pull/255 works for you?
