### ISSUE TITLE
Allow disabling of policy event logs

### ISSUE THREAD

**Issue by mycrEEpy** [aws/aws-network-policy-agent#47]
The collection of policy event logs is pretty expensive due to being a busy loop (using unix.EpollWait).

Users which are not interested in the logs (and/or are not willing to use a full CPU core on each node for the busy loop) should have the possibility to disable the policy event logs.

Furthermore I suggest the default behavior should be to disable the policy event logs due to the high cost factor.

**Comment by jdn5126** [comment]
Closing now that VPC CNI v1.15.1 is released on GitHub: https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.15.1. This release contains the Network Policy agent v1.0.4 image tag, which includes #48
