### ISSUE TITLE
Dump network policy event logs to stdout

### ISSUE THREAD

**Issue by sidewinder12s** [aws/aws-network-policy-agent#50]
Can these be configured to dump to stdout?

This is supported by the VPC CNI and will allow users to use pre-existing log collection frameworks within their clusters.

**Comment by jayanthvn** [comment]
It is not configurable with the initial version but we will add the flag to push the logs to stdout. Will open up a PR.

**Comment by mycrEEpy** [comment]
@sidewinder12s We already did this with `--log-file=/dev/stdout`

**Comment by jayanthvn** [comment]
Actually you are right @mycrEEpy. It is possible today by adding that flag for log file and log level but we don't yet support with managed add ons. Will track it as part of this issue..

**Comment by sidewinder12s** [comment]
It isn't clear to me either that that flag is for normal controller logs vs the policy decision logs, especially since with the cloud watch integration it sorta implies those logs are special.

**Comment by jayanthvn** [comment]
So the network policy node agent logs and policy decision logs are stored in file by default here - `/var/log/aws-routed-eni/network-policy-agent.log` (https://github.com/aws/aws-network-policy-agent/blob/main/pkg/config/controller_config.go#L10). But when CW is enabled then only policy decision logs gets streamed to CW and will be stored in the above log file.

**Comment by jdn5126** [comment]
Closing as it is possible to redirect the Network Policy agent logs to stdout today
