### ISSUE TITLE
CPU consumption

### ISSUE THREAD

**Issue by mkovsher** [aws/aws-network-policy-agent#54]
Image: aws-network-policy-agent:v1.0.1
Kubernetes: 1.27.4
AWS instance type: t3.small (credit specification: standard).

When I set "enable-network-policy" to "true", the "CPU credit usage" doubled  and the "CPU credit balance" ends.
After that we have a CPU processor load ~100%. 

Is this feature so CPU-consumption? 
What can be done to reduce CPU consumption and not change the instance type or credit specification?

**Comment by jayanthvn** [comment]
This is similar to #47 

With enabling network policy, we initialize ring buffer and have a epoll wait to capture policy decision logs. We are looking into making it configurable maybe opt-in.

**Comment by jdn5126** [comment]
Closing now that VPC CNI v1.15.1 is released on GitHub: https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.15.1. This release contains the Network Policy agent v1.0.4 image tag, which allows for disabling policy event logs
