### ISSUE TITLE
Any plans for a GUI?

### ISSUE THREAD

**Issue by yurrriq** [aws/aws-network-policy-agent#64]
When chaining Cilium as netpol engine on top of the AWS VPC CNI plugin, the Hubble UI is invaluable. Does AWS plan to implement any sort of GUI to accompany this project?

**Comment by jayanthvn** [comment]
@yurrriq - there is no plans right now for adding a UI but please open a request here - https://github.com/aws/containers-roadmap and we will provide updates.

**Comment by yurrriq** [comment]
Closing in favor of https://github.com/aws/containers-roadmap/issues/2144
