### ISSUE TITLE
aws-eks-nodeagent container fails with Exit code 1 on p3 instance types (nodes with GPU)

### ISSUE THREAD

**Issue by thelabdude** [aws/aws-network-policy-agent#89]
When running the `aws-node` DS pod on a `p3.8xlarge` on EKS 1.24, the `aws-eks-nodeagent` crashes with little useful information in the log. It works fine on all other nodes in my cluster (non-p3). The only solution I've found is to disable the container using: ` --enable-network-policy=false`

```
  aws-eks-nodeagent:
    Container ID:  containerd://9eaad2c891fdefcecc854aeb453f1077d0416c091cca7d3741e20219ca0e2018
    Image:         602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-network-policy-agent:v1.0.2
    Image ID:      602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-network-policy-agent@sha256:71fbb862ba51217f4c8a22502cba6fa8baa098b80590ea753378694b7c82a4db
    Port:          <none>
    Host Port:     <none>
    Args:
      --enable-ipv6=false
      --enable-cloudwatch-logs=false
      --metrics-bind-addr=:8162
      --health-probe-bind-addr=:8163
      --enable-network-policy=true
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 05 Oct 2023 10:48:11 -0600
      Finished:     Thu, 05 Oct 2023 10:48:12 -0600
```

**Comment by jayanthvn** [comment]
@thelabdude - Can you please check if bpf file system is mounted?


https://docs.aws.amazon.com/eks/latest/userguide/cni-network-policy.html
```
Mount the BPF filesystem

Note
If your cluster is version 1.27 or later, you can skip this step as all Amazon EKS optimized Amazon Linux and Bottlerocket AMIs for 1.27 or later have this feature already.
For all other cluster versions, if you upgrade the Amazon EKS optimized Amazon Linux to version v20230703 or later or you upgrade the Bottlerocket AMI to version v1.0.2 or later, you can skip this step.
Mount the Berkeley Packet Filter (BPF) file system on each of your nodes.

sudo mount -t bpf bpffs /sys/fs/bpf

```

**Comment by thelabdude** [comment]
Thanks for quick response @jayanthvn ... so actually ran that command twice (sorry I missed that step), but mount is showing: 
```
mount -t bpf
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
none on /sys/fs/bpf type bpf (rw,relatime)
none on /sys/fs/bpf type bpf (rw,relatime)
```
and pod is still failing with same behavior. I'm going to try upgrading to the latest AMI for GPU to see if that makes a difference here.

**Comment by thelabdude** [comment]
I just updated to AMI based on `amazon-eks-gpu-node-1.24-v20230919` and same error result, on that node:
```
mount -t bpf
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)

mount -t bpf bpffs /sys/fs/bpf
mount -t bpf
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
none on /sys/fs/bpf type bpf (rw,relatime)
```

**Comment by thelabdude** [comment]
so this is interesting ... the previous p3 instance was removed by cluster auto-scaler and the new instance that came back once we spun up another pod needing the GPU didn't have this problem ... very weird.

**Comment by jayanthvn** [comment]
GPU AMIs are not supported yet for Network Policy since we need 5.10 kernel version for ring buffer.

**Comment by sjastis** [comment]
Support for VPC CNI network policy in GPU instances is now available starting with [1].

[1] https://github.com/awslabs/amazon-eks-ami/releases/tag/v20231116
