### ISSUE TITLE
Network Policy Agent support on GPU instances

### ISSUE THREAD

**Issue by seanturner026** [aws/aws-network-policy-agent#91]
**What happened**:

A routine upgrade of the VPC CNI Addon from `1.13.4` --> `1.14.0` and today `1.14.1` has failed both times. The logs do not reveal anything but are below.

The Addon configuration is as follows:

```json
{
  "enableNetworkPolicy": "true",
  "env": {
    "ENABLE_POD_ENI": "true"
  },
  "init": {
    "env": {
      "DISABLE_TCP_EARLY_DEMUX": "true"
    }
  }
}
```

We have Nodes in our Production cluster with GPUs (specifically `p3.2xlarge`). The `aws-node` Pod on these Nodes will quickly end up in a `CrashLoopBackOff` once the update is deployed to the Node. This `CrashLoopBackOff` status will prevent the VPC CNI addon from becoming healthy for ~1.5-2 hours. At that point, we are able to return to `1.13.4` with the `enableNetworkPolicy` configuration removed without issue.

Once I realized that the GPU Nodes were the problem, I spun up a staging node in our staging cluster and saw the same behavior, the `aws-node` Pod will `CrashLoopBackOff`. This upgrade was able to proceed without issue in staging because we do not usually run GPU workloads there. This pod was launched with jupyterhub, and interestingly, the `CrashLoopBackOff` didn't seem to affect much, the Jupyterhub notebook was still able to start without issue. I suppose this would cause issues with `NetworkPolicies`?

**Attach logs**

```
$ kl aws-node-q5ppr
Defaulted container "aws-node" out of: aws-node, aws-eks-nodeagent, aws-vpc-cni-init (init)
Installed /host/opt/cni/bin/aws-cni
Installed /host/opt/cni/bin/egress-cni
time="2023-09-26T12:55:56Z" level=info msg="Starting IPAM daemon... "
time="2023-09-26T12:55:56Z" level=info msg="Checking for IPAM connectivity... "
time="2023-09-26T12:55:58Z" level=info msg="Copying config file... "
time="2023-09-26T12:55:58Z" level=info msg="Successfully copied CNI plugin binary and config file."
```
```
$ kl aws-node-q5ppr aws-eks-nodeagent
{"level":"info","ts":"2023-09-26T13:37:18Z","msg":"version","GitVersion":"","GitCommit":"","BuildDate":""}
```
```
$ kl aws-node-q5ppr aws-vpc-cni-init
time="2023-09-26T12:55:55Z" level=info msg="Copying CNI plugin binaries ..."
time="2023-09-26T12:55:55Z" level=info msg="Copied all CNI plugin binaries to /host/opt/cni/bin"
time="2023-09-26T12:55:55Z" level=info msg="Found primaryMAC 02:38:a4:a0:15:4f"
time="2023-09-26T12:55:55Z" level=info msg="Found primaryIF eth0"
time="2023-09-26T12:55:55Z" level=info msg="Updated net/ipv4/conf/eth0/rp_filter to 2\n"
time="2023-09-26T12:55:55Z" level=info msg="Updated net/ipv4/tcp_early_demux to 0\n"
time="2023-09-26T12:55:55Z" level=info msg="CNI init container done"
```

**What you expected to happen**:

I expected the VPC CNI upgrade to proceed without issue.

**How to reproduce it (as minimally and precisely as possible)**:

Spin up a node with a GPU attached with the VPC CNI plugin on version 1.14.1 with the below configuration. At this point in time, I am unsure if it it the `1.14.1` version that is breaking GPU nodes, or, if the `"enableNetworkPolicy": "true"` configuration is breaking things.

```json
{
  "enableNetworkPolicy": "true",
  "env": {
    "ENABLE_POD_ENI": "true"
  },
  "init": {
    "env": {
      "DISABLE_TCP_EARLY_DEMUX": "true"
    }
  }
}
```

**Anything else we need to know?**:

**Environment**: production
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:24Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.7-eks-2d98532", GitCommit:"c9c3fc1fdf677f38b8d26568c10b921a1235fa43", GitTreeState:"clean", BuildDate:"2023-07-28T16:51:21Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```
- CNI Version: `1.14.1`
- OS (e.g: `cat /etc/os-release`): AMI is `amazon-eks-gpu-node-1.26-v20230607`
- Kernel (e.g. `uname -a`):

**Comment by jayanthvn** [comment]
GPU AMIs are not supported yet for Network Policy. Similar to #89

**Comment by sjastis** [comment]
Support for VPC CNI network policy in GPU instances is now available starting with [1].

[1] https://github.com/awslabs/amazon-eks-ami/releases/tag/v20231116
